"""First

Revision ID: f9fab8a0b3ae
Revises:
Create Date: 2025-01-30 00:07:14.303404

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9fab8a0b3ae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintable",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("staking_dollars", sa.Float(), nullable=False),
        sa.Column("staking_ebc", sa.Float(), nullable=False),
        sa.Column("staking_holders", sa.Float(), nullable=False),
        sa.Column("ebc_value", sa.Float(), nullable=False),
        sa.Column("market_cap", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_maintable_id"), "maintable", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_maintable_id"), table_name="maintable")
    op.drop_table("maintable")
    # ### end Alembic commands ###
